appName: monitor
apiVersion: v0.0.0
baseUrl: http://localhost:3007/rest
serviceUrlPrefix: /rest
servicesRoot: services
services:
    - /monitoring/isAlive

loginCredentials:
    user: username
    pass: password
