projectName: {{projectName}}
apiVersion: v0.0.0
author: {{author}}
licence: {{licence}}
serviceUrlPrefix: {{urlPrefix}}
servicePort: {{port}}
baseUrl: http://localhost:{{port}}{{urlPrefix}}
servicesRoot: {{servicesRoot}}
services:
    - /monitoring/isAlive
    # To add new services, put here the path of the directory that contains the service.yml

loginCredentials:
    user: {{username}}
    pass: {{password}}
